# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBAtJub8gP026Q4oEHSL0do0v3KqwfAc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import requests

url = "https://transparencia.arraial.modernizacao.com.br/sincronia/apidados.rule?sys=LAI"

payload = {
    "api": "despesas_todas",
    "ano": 2025
}

response = requests.post(url, json=payload)

data = response.json()

print(len(data["dados"]))  # quantos registros vieram
print(data["dados"][0])    # ver um exemplo

print(data)

df = pd.DataFrame(data["dados"])

df.head()

df.info()

df['valor_despesa']= df['valor_despesa'].astype(float)
df['Valor_Estornado'] =df['Valor_Estornado'].astype(float)
df['valor_despesa_total']= df['valor_despesa_total'].astype(float)
df['data_despesa'] = pd.to_datetime(df['data_despesa'])
df['valor_liquidado'] = df['valor_liquidado'].astype(float)
df['valor_estorno_liquidacao']= df['valor_estorno_liquidacao'].astype(float)
df['valor_retido']= df['valor_retido'].astype(float)
df['valor_estorno_pagamento']= df['valor_estorno_pagamento'].astype(float)
df['valor_pago_liquido']= df['valor_pago_liquido'].astype(float)

df['valor_despesa'].sum()

df['valor_despesa'].groupby(df['orgao']).sum().sort_values(ascending=False)

df['valor_despesa'].groupby(df['descricao_favorecido']).sum().sort_values(ascending=False)

df['valor_despesa'].groupby(df['nome_secretria']).sum().sort_values(ascending=False)

df['valor_despesa'].groupby(df['data_despesa'].dt.month).sum()

df['valor_despesa'].groupby(df['data_despesa'].dt.month).sum().plot(kind='bar')

filter = df['Tipo'] == 'J'

df_filtrado = df[filter]
df_filtrado

df_filtrado['valor_despesa'].groupby(df_filtrado['descricao_favorecido']).sum().sort_values(ascending=False)

filter_primaqualit= df['descricao_favorecido'] =="PROJETO SOCIAL CRESCE COMUNIDADE - PRIMA QUALITA"
filter_primaqualit

df_PRIMA_QUALITA = df[filter_primaqualit]
df_PRIMA_QUALITA

df_PRIMA_QUALITA['valor_despesa'].groupby(df_PRIMA_QUALITA['data_despesa'].dt.month).sum()